<?php

namespace Database\Seeders;

use App\Models\Doctor;
use Illuminate\Database\Seeder;

class DoctorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $doctors = [
            [
                'id' => 1,
                'name' => 'Dr. Robert Chambers',
                'available_days' => json_encode(['Sunday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 1,
                    'name' => 'Square Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 1,
                    'name' => 'Pediatrics',
                    'image' => 'https://i.pravatar.cc/150?img=1',
                ],
            ],
            [
                'id' => 2,
                'name' => 'Dr. Brian Collins',
                'available_days' => json_encode(['Wednesday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 1,
                    'name' => 'Square Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 2,
                    'name' => 'Gastroenterology',
                    'image' => 'https://i.pravatar.cc/150?img=3',
                ],
            ],
            [
                'id' => 3,
                'name' => 'Dr. Meredith Copeland',
                'available_days' => json_encode(['Monday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 1,
                    'name' => 'Square Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=12',
                ],
            ],
            [
                'id' => 4,
                'name' => 'Dr. Shannon Brown',
                'available_days' => json_encode(['Sunday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 1,
                    'name' => 'Square Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 4,
                    'name' => 'Dermatology',
                    'image' => 'https://i.pravatar.cc/150?img=46',
                ],
            ],
            [
                'id' => 5,
                'name' => 'Dr. Cindy Ward',
                'available_days' => json_encode(['Monday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 1,
                    'name' => 'Square Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 5,
                    'name' => 'Oncology',
                    'image' => 'https://i.pravatar.cc/150?img=15',
                ],
            ],
            [
                'id' => 6,
                'name' => 'Dr. Rachel Jones',
                'available_days' => json_encode(['Sunday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 2,
                    'name' => 'Labaid Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 6,
                    'name' => 'ENT',
                    'image' => 'https://i.pravatar.cc/150?img=70',
                ],
            ],
            [
                'id' => 7,
                'name' => 'Dr. Matthew Horton',
                'available_days' => json_encode(['Wednesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 2,
                    'name' => 'Labaid Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 7,
                    'name' => 'Nephrology',
                    'image' => 'https://i.pravatar.cc/150?img=6',
                ],
            ],
            [
                'id' => 8,
                'name' => 'Dr. Andrew Jones',
                'available_days' => json_encode(['Tuesday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 2,
                    'name' => 'Labaid Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=31',
                ],
            ],
            [
                'id' => 9,
                'name' => 'Dr. Sarah Bailey',
                'available_days' => json_encode(['Sunday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 2,
                    'name' => 'Labaid Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 7,
                    'name' => 'Nephrology',
                    'image' => 'https://i.pravatar.cc/150?img=30',
                ],
            ],
            [
                'id' => 10,
                'name' => 'Dr. Scott Barnes',
                'available_days' => json_encode(['Sunday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 2,
                    'name' => 'Labaid Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=68',
                ],
            ],
            [
                'id' => 11,
                'name' => 'Dr. Leroy Dunn',
                'available_days' => json_encode(['Tuesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 3,
                    'name' => 'United Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=58',
                ],
            ],
            [
                'id' => 12,
                'name' => 'Dr. Alicia Gaines',
                'available_days' => json_encode(['Thursday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 3,
                    'name' => 'United Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=8',
                ],
            ],
            [
                'id' => 13,
                'name' => 'Dr. Nathan Cortez MD',
                'available_days' => json_encode(['Tuesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 3,
                    'name' => 'United Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 6,
                    'name' => 'ENT',
                    'image' => 'https://i.pravatar.cc/150?img=44',
                ],
            ],
            [
                'id' => 14,
                'name' => 'Dr. Robert Adams',
                'available_days' => json_encode(['Monday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 3,
                    'name' => 'United Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=49',
                ],
            ],
            [
                'id' => 15,
                'name' => 'Dr. Charles Wheeler',
                'available_days' => json_encode(['Thursday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 4,
                    'name' => 'Ibn Sina Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=23',
                ],
            ],
            [
                'id' => 16,
                'name' => 'Dr. Kristen Foster',
                'available_days' => json_encode(['Sunday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 4,
                    'name' => 'Ibn Sina Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=49',
                ],
            ],
            [
                'id' => 17,
                'name' => 'Dr. Cheryl Hansen',
                'available_days' => json_encode(['Thursday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 4,
                    'name' => 'Ibn Sina Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=35',
                ],
            ],
            [
                'id' => 188,
                'name' => 'Dr. Jill Sheppard',
                'available_days' => json_encode(['Sunday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 4,
                    'name' => 'Ibn Sina Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=35',
                ],
            ],
            [
                'id' => 19,
                'name' => 'Dr. Randy Holt',
                'available_days' => json_encode(['Sunday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 4,
                    'name' => 'Ibn Sina Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=15',
                ],
            ],
            [
                'id' => 20,
                'name' => 'Dr. Tina Tucker',
                'available_days' => json_encode(['Wednesday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 5,
                    'name' => 'Dhaka Medical College Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=36',
                ],
            ],
            [
                'id' => 21,
                'name' => 'Dr. Ryan Walker',
                'available_days' => json_encode(['Sunday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 5,
                    'name' => 'Dhaka Medical College Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 6,
                    'name' => 'ENT',
                    'image' => 'https://i.pravatar.cc/150?img=17',
                ],
            ],
            [
                'id' => 22,
                'name' => 'Dr. Jessica Williams',
                'available_days' => json_encode(['Wednesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 5,
                    'name' => 'Dhaka Medical College Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 4,
                    'name' => 'Dermatology',
                    'image' => 'https://i.pravatar.cc/150?img=33',
                ],
            ],
            [
                'id' => 23,
                'name' => 'Dr. Johnathan Jones',
                'available_days' => json_encode(['Wednesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 5,
                    'name' => 'Dhaka Medical College Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 4,
                    'name' => 'Dermatology',
                    'image' => 'https://i.pravatar.cc/150?img=20',
                ],
            ],
            [
                'id' => 24,
                'name' => 'Dr. Timothy Gonzalez',
                'available_days' => json_encode(['Wednesday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 5,
                    'name' => 'Dhaka Medical College Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 2,
                    'name' => 'Gastroenterology',
                    'image' => 'https://i.pravatar.cc/150?img=21',
                ],
            ],
            [
                'id' => 25,
                'name' => 'Dr. Anna Cervantes',
                'available_days' => json_encode(['Sunday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 6,
                    'name' => 'Popular Diagnostic Center',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 5,
                    'name' => 'Oncology',
                    'image' => 'https://i.pravatar.cc/150?img=21',
                ],
            ],
            [
                'id' => 26,
                'name' => 'Dr. Joanna Gregory',
                'available_days' => json_encode(['Wednesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 6,
                    'name' => 'Popular Diagnostic Center',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 2,
                    'name' => 'Gastroenterology',
                    'image' => 'https://i.pravatar.cc/150?img=42',
                ],
            ],
            [
                'id' => 27,
                'name' => 'Dr. Derek Cameron',
                'available_days' => json_encode(['Wednesday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 6,
                    'name' => 'Popular Diagnostic Center',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 10,
                    'name' => 'Orthopedics',
                    'image' => 'https://i.pravatar.cc/150?img=26',
                ],
            ],
            [
                'id' => 28,
                'name' => 'Dr. Tyler Stephens',
                'available_days' => json_encode(['Wednesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 6,
                    'name' => 'Popular Diagnostic Center',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 4,
                    'name' => 'Dermatology',
                    'image' => 'https://i.pravatar.cc/150?img=8',
                ],
            ],
            [
                'id' => 29,
                'name' => 'Dr. James Dennis',
                'available_days' => json_encode(['Thursday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 6,
                    'name' => 'Popular Diagnostic Center',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 1,
                    'name' => 'Pediatrics',
                    'image' => 'https://i.pravatar.cc/150?img=53',
                ],
            ],
            [
                'id' => 30,
                'name' => 'Dr. Roy Galvan',
                'available_days' => json_encode(['Thursday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 7,
                    'name' => 'BSMMU (PG Hospital)',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=6',
                ],
            ],
            [
                'id' => 31,
                'name' => 'Dr. Michael Rodriguez',
                'available_days' => json_encode(['Wednesday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 7,
                    'name' => 'BSMMU (PG Hospital)',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 10,
                    'name' => 'Orthopedics',
                    'image' => 'https://i.pravatar.cc/150?img=41',
                ],
            ],
            [
                'id' => 32,
                'name' => 'Dr. Mary Johnson',
                'available_days' => json_encode(['Wednesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 7,
                    'name' => 'BSMMU (PG Hospital)',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=29',
                ],
            ],
            [
                'id' => 33,
                'name' => 'Dr. Jeremy Arnold',
                'available_days' => json_encode(['Tuesday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 7,
                    'name' => 'BSMMU (PG Hospital)',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 7,
                    'name' => 'Nephrology',
                    'image' => 'https://i.pravatar.cc/150?img=16',
                ],
            ],
            [
                'id' => 34,
                'name' => 'Dr. Yolanda Wilkerson',
                'available_days' => json_encode(['Monday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 7,
                    'name' => 'BSMMU (PG Hospital)',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=13',
                ],
            ],
            [
                'id' => 35,
                'name' => 'Dr. Charles Lopez',
                'available_days' => json_encode(['Monday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 8,
                    'name' => 'Evercare Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 7,
                    'name' => 'Nephrology',
                    'image' => 'https://i.pravatar.cc/150?img=25',
                ],
            ],
            [
                'id' => 36,
                'name' => 'Dr. Tyler Jones',
                'available_days' => json_encode(['Tuesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 8,
                    'name' => 'Evercare Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=22',
                ],
            ],
            [
                'id' => 37,
                'name' => 'Dr. Roger Andrews',
                'available_days' => json_encode(['Wednesday', 'Tuesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 8,
                    'name' => 'Evercare Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 2,
                    'name' => 'Gastroenterology',
                    'image' => 'https://i.pravatar.cc/150?img=53',
                ],
            ],
            [
                'id' => 38,
                'name' => 'Dr. Kelsey Garcia',
                'available_days' => json_encode(['Tuesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 8,
                    'name' => 'Evercare Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=66',
                ],
            ],
            [
                'id' => 39,
                'name' => 'Dr. Tammy Lewis',
                'available_days' => json_encode(['Sunday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 8,
                    'name' => 'Evercare Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 3,
                    'name' => 'Neurology',
                    'image' => 'https://i.pravatar.cc/150?img=62',
                ],
            ],
            [
                'id' => 40,
                'name' => 'Dr. Gregory Diaz',
                'available_days' => json_encode(['Tuesday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 9,
                    'name' => 'Birdem General Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=21',
                ],
            ],
            [
                'id' => 41,
                'name' => 'Dr. Brian Maldonado',
                'available_days' => json_encode(['Tuesday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 9,
                    'name' => 'Birdem General Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 1,
                    'name' => 'Pediatrics',
                    'image' => 'https://i.pravatar.cc/150?img=13',
                ],
            ],
            [
                'id' => 42,
                'name' => 'Dr. Andrew Mcmillan DDS',
                'available_days' => json_encode(['Wednesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 9,
                    'name' => 'Birdem General Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=24',
                ],
            ],
            [
                'id' => 43,
                'name' => 'Dr. Logan Higgins',
                'available_days' => json_encode(['Tuesday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 9,
                    'name' => 'Birdem General Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=24',
                ],
            ],
            [
                'id' => 44,
                'name' => 'Dr. David Guzman',
                'available_days' => json_encode(['Sunday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 9,
                    'name' => 'Birdem General Hospital',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=2',
                ],
            ],
            [
                'id' => 45,
                'name' => 'Dr. Ryan Hudson',
                'available_days' => json_encode(['Sunday', 'Monday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 10,
                    'name' => 'National Heart Foundation',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=8',
                ],
            ],
            [
                'id' => 46,
                'name' => 'Dr. Lauren Mccormick',
                'available_days' => json_encode(['Monday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 25,
                'hospital' => [
                    'id' => 10,
                    'name' => 'National Heart Foundation',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 9,
                    'name' => 'Psychiatry',
                    'image' => 'https://i.pravatar.cc/150?img=41',
                ],
            ],
            [
                'id' => 47,
                'name' => 'Dr. Christian Wells',
                'available_days' => json_encode(['Tuesday', 'Wednesday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 10,
                    'name' => 'National Heart Foundation',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 8,
                    'name' => 'Cardiology',
                    'image' => 'https://i.pravatar.cc/150?img=58',
                ],
            ],
            [
                'id' => 48,
                'name' => 'Dr. Joshua Lin',
                'available_days' => json_encode(['Wednesday', 'Sunday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 30,
                'hospital' => [
                    'id' => 10,
                    'name' => 'National Heart Foundation',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 7,
                    'name' => 'Nephrology',
                    'image' => 'https://i.pravatar.cc/150?img=66',
                ],
            ],
            [
                'id' => 49,
                'name' => 'Dr. Dylan Brooks DVM',
                'available_days' => json_encode(['Monday', 'Thursday']),
                'start_time' => '09:00',
                'end_time' => '14:00',
                'max_patients_per_day' => 20,
                'hospital' => [
                    'id' => 10,
                    'name' => 'National Heart Foundation',
                    'district' => 'Dhaka',
                ],
                'speciality' => [
                    'id' => 1,
                    'name' => 'Pediatrics',
                    'image' => 'https://i.pravatar.cc/150?img=63',
                ],
            ],
        ];

        foreach ($doctors as $doctor) {
            Doctor::create([
                'name' => $doctor['name'],
                'available_days' => $doctor['available_days'],
                'start_time' => $doctor['start_time'],
                'end_time' => $doctor['end_time'],
                'max_patients_per_day' => $doctor['max_patients_per_day'],
                'hospital_id' => $doctor['hospital']['id'],
                'speciality_id' => $doctor['speciality']['id'],
                'image' => $doctor['speciality']['image'],
            ]);
        }
    }
}
